### ISSUE TITLE
Report a bug in torgo_data_prep.sh

### ISSUE THREAD

**Issue by Baileyswu** [idiap/torgo_asr#1]
https://github.com/idiap/torgo_asr/blob/3e8a144364ee8d14b74b9b7c264757418a38db1a/local/torgo_data_prep.sh#L70

Not everyone put his torgo dataset at a directory which ends with 'data/'.
It will cause trouble when one name his data directory as 'TORGO' or sth else.
Better to fix it by
```
tmp=${session#*$CORPUS/}
```

**Comment by Baileyswu** [comment]
it's urgent because it will cause a wrong value of gender.
https://github.com/idiap/torgo_asr/blob/3e8a144364ee8d14b74b9b7c264757418a38db1a/local/torgo_data_prep.sh#L74

**Comment by eginhard** [comment]
Thanks for letting me know and proposing the fix as well! I checked the files available on the corpus website and they indeed do not contain a `data` directory, so our local version might be older and organised differently. I updated that script.
